inherit_from:
  - https://github.com/onk/onkcop/raw/v0.52.0.0/config/rubocop.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/**/*'

# TODO: Remove this config after droping Ruby 2.2 support
Layout/IndentHeredoc:
  Include:
    - 'test/**/*'

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/Semicolon:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Enabled: false

Metrics/LineLength:
  Max: 200
  Exclude:
    # To use power_assert, we must pub assertion in one line
    - 'test/**/*'
