version: 2
jobs:
  ruby-2-6: &test
    docker:
      - image: tmaier/docker-compose
        environment:
          COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: setup
          command: |
            set -x
            docker info
            docker volume create project
            docker create -v project:/app --name project busybox chown -R 1000:1000 /app
            docker cp . project:/app
            docker start project
            docker-compose build $CIRCLE_JOB
      - run: docker-compose run $CIRCLE_JOB bin/ci
  ruby-2-5:
    <<: *test
  ruby-2-4:
    <<: *test
  ruby-2-3:
    <<: *test
  ruby-2-2:
    <<: *test
  test-docker-build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: docker build .
workflows:
  version: 2
  test:
    jobs:
      - ruby-2-6
      - ruby-2-5
      - ruby-2-4
      - ruby-2-3
      - ruby-2-2
      - test-docker-build
